version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/onozaty/filep/cmd.Version={{.Version}}
      - -X github.com/onozaty/filep/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Tag }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

homebrew_casks:
  - repository:
      owner: onozaty
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    description: "A powerful command-line file processing tool"
    homepage: "https://github.com/onozaty/filep"
    license: MIT
    skip_upload: auto

scoops:
  - repository:
      owner: onozaty
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    description: "A powerful command-line file processing tool"
    homepage: "https://github.com/onozaty/filep"
    license: MIT
    skip_upload: auto
